### ISSUE TITLE
Missing partial _favicon in production

### ISSUE THREAD

**Issue by RobinOBrien** [RealFaviconGenerator/rails_real_favicon#10]
Worked flawlessly in dev environment. Same code in production throws a Missing partial exception.

The images have compiled correctly to public/assets.

Added the _render 'favicon'_ tag to the application.html.erb file within the html head tags.

I have nested the generated favicons inside images/favicon/ directory. Compensated for the change by trying _render 'favicon/favicon_ but this did not help either.

**Comment by sambrannon** [comment]
Just ran into this myself...

```
rails generate favicon
```

places the favicon partial into `views/application/_favicon.html.erb` but the provided instructions say to use `<%= render 'favicon' %>`...

It was working in my dev environment as well, but to fix it I had to set the path more specifically to

```
<%= render 'application/favicon' %>
```

This fixed it in dev and now works in production as well.

**Comment by phbernard** [comment]
Now that the instructions are generated correctly, that should never happen again!

Thank you again @sambrannon for providing the solution.
