### ISSUE TITLE
Bump Gemspec

### ISSUE THREAD

**Issue by lordofthedanse** [RealFaviconGenerator/rails_real_favicon#12]
The pessimistic lock on the JSON dependence (`json (~> 1.7)`) causes incompatibility with other gems (for me, `simplecov`), as the most current `json` release is now `2.0.2.` as of July 2016. The last version of `1.7` was released in February 2013.

I recommend: 
```
s.add_dependency "json", “>= 1.7", "< 3”
```

**Comment by lordofthedanse** [comment]
@phbernard btw and FYI, I tried to open a PR for this but the repository permissions wouldn’t allow it.

**Comment by phbernard** [comment]
Fixed! Thanks for reporting.

No PR, really? Alright, I'll investigate this.

**Comment by lordofthedanse** [comment]
Hey – happy to help. Thanks for the gem!
