### ISSUE TITLE
Reading master_file and received files is failing if they are binary

### ISSUE THREAD

**Issue by bradlis7** [RealFaviconGenerator/rails_real_favicon#15]
I'm not sure if this is a windows bug, but I'm not able to generate with a PNG file. `File.read(master_pic)` assumes the file is text, and only reads a few lines. Need to change it to this:

    File.open(master_pic, "rb") do |f|
      req['master_picture']['content'] = Base64.encode64(f.read)
    end

I'm also seeing an issue after generating where the PNG files are only 5KB, and the issue seems to be the same. Line 39 should be changed from `content = File.read(file)` to `content = File.open(file, "rb") { |f| f.read }`

I can do a pull request. Not sure if my code is the shortest option.

**Comment by bradlis7** [comment]
`File.binread` would work and be shorter.

**Comment by phbernard** [comment]
Thank you for the PR! Merged and published (0.0.7)
