### ISSUE TITLE
400 Bad Request with non-square images

### ISSUE THREAD

**Issue by hellojere** [RealFaviconGenerator/rails_real_favicon#2]
When trying to generate the favicons through command line the following error occurs if the image is not exactly 1:1 in ratio. 

```
400 Bad Request (RestClient::BadRequest)
```

Great gem though!

**Comment by phbernard** [comment]
You're right, non-square pictures should be accepted. This issue is not related with the gem but with the API. I entered https://github.com/RealFaviconGenerator/realfavicongenerator/issues/203

Thank you for your feedback! This is the very first feedback I get for the Rails extension!
