### ISSUE TITLE
The favicon dosen't show in production mode

### ISSUE THREAD

**Issue by PedroPauloML** [RealFaviconGenerator/rails_real_favicon#20]
Hello! This is not a doubt , but a hint about this error.
I deployed my application in Heroku and used the "rails_real_favicon" to set the icon of my application. But, when I deploy and the Heroku set the `RAILS_ENV` as `production`, the favicon dosen't show.
The problem is on type of favicon. The own Heroku presents the solution in his [git ](https://github.com/heroku/favicon). You only need change the type of the favicons, in `views/application/_favicon.html.erb`, to `image/vnd.microsoft.icon`.
Just that!

This was the solution for me.

Is the tip!

**Comment by phbernard** [comment]
Hi Pedro,

Thanks for the tip!

Well I don't reproduce the issue. [MonitorBoy](https://monitorboy.com/) is a Rails app hosted on Heroku, it uses [rails_real_favicon](https://github.com/RealFaviconGenerator/rails_real_favicon) as is and the favicon shows up as expected.

Which browser did you use to observe the problem?

**Comment by PedroPauloML** [comment]
I used the Google Chrome. @phbernard

**Comment by piedoom** [comment]
Try on a different computer or browser, Pedro.  Often Chrome has some very weird caching issues with favicons, where it will appear with others but not yourself.

**Comment by phbernard** [comment]
I think we can close this one.
