### ISSUE TITLE
Getting 400

### ISSUE THREAD

**Issue by julien51** [RealFaviconGenerator/rails_real_favicon#4]
```
$ rails generate favicon
/Users/julien/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!': 400 Bad Request (RestClient::BadRequest)
    from /Users/julien/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
    from /Users/julien/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
    from /Users/julien/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:853:in `start'
```

**Comment by phbernard** [comment]
Thank you for reporting.

Could you join:
- Your `favicon.json` file
- Your master picture

If you don't want to disclose this here, you can mail me these docs at contact@realfavicongenerator.net

**Comment by phbernard** [comment]
(I just got your stuff by email)

This is because the API wrongly assumes your picture is in PNG format, which is not. I'm not sure what's wrong here (the API does accept SVG pics), but at least I have everything I need to fix.

**Comment by phbernard** [comment]
Alright, it works now. Re-open the issue if it's still wrong on your side but I could generate your favicon with your picture and JSON file.

Internally, RFG is using ImageMagick `indentify` command. `identify` is smart enough to sort out PNG and SVG, even if the extension is wrong:

```
identify svg_pic.svg
svg_pic.svg  SVG 800x800 800x800+0+0 8-bit sRGB 30.5KB 0.000u 0:00.000
mv svg_pic.svg svg_pic.png # Oops!
identify svg_pic.png
svg_pic.png SVG 800x800 800x800+0+0 8-bit sRGB 30.5KB 0.000u 0:00.000
```

Until now, RFG has relied on this feature to detect the actual picture encoding.

For some reasons, that doesn't work with your picture:

```
identify your_svg_pic_with_wrong_extension.png
identify: improper image header `your_svg_pic_with_wrong_extension.png' @ error/png.c/ReadPNGImage/3921.
```

So I've just added error cases to make the process more resilient.
