### ISSUE TITLE
Add "short_name" in android manifest

### ISSUE THREAD

**Issue by pefringant** [RealFaviconGenerator/rails_real_favicon#6]
I am trying to define the "short_name" of my app according to the Chrome doc :

https://developers.google.com/web/updates/2014/11/Support-for-installable-web-apps-with-webapp-manifest-in-chrome-38-for-Android

When I add the short_name key in config/favicon.json, the resulting manifest does not show the short_name.

**Comment by pefringant** [comment]
In fact it could be useful to allow any key/value pair in the android chrome manifest part.

**Comment by phbernard** [comment]
I suggest you to use the `existing_manifest` setting. Basically, you create a manifest of your own, with a `short_name` and whatever other members you want. Then, you pass it as an existing manifest. RFG will patch it with its own attributes (the icons, etc.). Also use the `on_conflict` member to specify what should happen when RFG tries to update an existing attribute (eg. for the day RFG generates `short_name` too).

More about this in the [non-interactive API doc](https://realfavicongenerator.net/api/non_interactive_api).

**Comment by pefringant** [comment]
Thank you Philippe, it works perfectly.

**Comment by phbernard** [comment]
Great! Thanks for closing this one :)
