### ISSUE TITLE
Server Timeout

### ISSUE THREAD

**Issue by adamdebono** [RealFaviconGenerator/rails_real_favicon#9]
I am getting server timeout issues trying to generate my favicon.

I am using rails 5.0.0

Error Output below:

```
~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-2.0.0/lib/restclient/request.rb:784:in `rescue in transmit': Timed out reading data from server (RestClient::Exceptions::ReadTimeout)
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-2.0.0/lib/restclient/request.rb:698:in `transmit'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-2.0.0/lib/restclient/request.rb:215:in `execute'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-2.0.0/lib/restclient/request.rb:52:in `execute'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-2.0.0/lib/restclient.rb:71:in `post'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rails_real_favicon-0.0.5/lib/generators/favicon_generator.rb:26:in `generate_favicon'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-5.0.0/lib/rails/generators.rb:180:in `invoke'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-5.0.0/lib/rails/commands/generate.rb:13:in `<top (required)>'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:138:in `require_command!'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:145:in `generate_or_destroy'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:60:in `generate'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from ~/Documents/workspace/wizard-of-odds/wizard-of-odds-sports/bin/rails:9:in `<top (required)>'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `block in load'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
    from ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
    from ~/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from ~/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from -e:1:in `<main>'
```

**Comment by phbernard** [comment]
I don't reproduce the issue: 
- I've just created a sample Rails 5 project, installed RFG's stuff as documented and generated the icons successfully.
- I didn't notice anything wrong in the logs today. But logs are huge and I can't pretend I reviewed every possible issue.

However, when I tested the gem with the sample Rails 5 project, I had to disable Spring. I don't understand why, as I have successfully run the procedure in the past. But maybe you should give this a try. Please let me know if that changes anything.

**Comment by adamdebono** [comment]
tried that, same result.

**Comment by adamdebono** [comment]
I have also tried replicating the request using curl to make sure that it isn't anything to do with my network connection, and that seemed to work fine.

**Comment by phbernard** [comment]
This issue is rather old, I guess it can be closed. Of course, re-open it again if there is something to add.

**Comment by surfermicha** [comment]
I have this issue, too. What was the solution here?

**Comment by phbernard** [comment]
I've run the command a minute ago, worked as expected. And as far as I know, there was no issue with the service during the last few months.

Do you still face the problem?

**Comment by surfermicha** [comment]
Yes, I still have this problem. Maybe the cause is that I'm programming rails on a windows machine?

FYI: This is the error message
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/rest-client-2.0.2-x86-mingw32/lib/restclient/request.rb:733:in `rescue in transmit': Timed out reading data from server (Rest
Client::Exceptions::ReadTimeout)

**Comment by surfermicha** [comment]
Hello? Is someone still there?
I also tried to generate from a linux virtualbox to exclude issues on windows, but i get the same result.
Any ideas?

**Comment by phbernard** [comment]
Hi,

I can't reproduce the issue. I've just run `rails g favicon` successfully.

It might come from a timeout setting issue. The favicon generation request is rather long. If, for some reason, your system is not patient enough, you might get a timeout whereas a longer wait could have made it. I don't now how `Net::HTTP.start` is working to this regards (ie. if the timeout could be different on our respective systems). In any case, setting `read_timeout` explicitly in the call to `Net::HTTP.start` (in `lib/generators/favicon_generator.rb`) might be the way to go.

Is this something you could try?

**Comment by surfermicha** [comment]
Thanks for your super fast answer! I tried that (with a 240sec timeout) but I still get the ReadTimeout error.
How long does the request take in you application?

Which ruby version do you use? Might that be a problem?

**Comment by surfermicha** [comment]
Even with 480sec the same error

**Comment by phbernard** [comment]
Wait, the service is not *that* slow :-)

It might be useful to run a few experiments such as:
- Can you ping RealFaviconGenerator?
- What if you hack the request URL and target RealFaviconGenerator's
homepage? (It should obviously fail but not with a timeout)
- If you still have a timeout with RFG's homepage, what about Google's
homepage?

Le mar. 19 févr. 2019 à 16:45, Michael Landreh <notifications@github.com> a
écrit :

**Comment by surfermicha** [comment]
I checkt that. It worked fine (got the expectes JSON.parse error) with google and with the homepage. only https://realfavicongenerator.net/api/favicon makes problems...

**Comment by surfermicha** [comment]
Do I need to open a special port for api access?

**Comment by surfermicha** [comment]
I also tried the request with the body from request.body and it works perfectly.
I don't know how the script itself doesn't work

**Comment by phbernard** [comment]
Thanks for running these experiments.

Okay so:

- The gem works as is on my station
- The request works when you run it manually
- The gem code works on your station when you hack the URL

I admit I'm a bit clueless :-/

**Comment by surfermicha** [comment]
I don't have a clue,too. But I worked around a bit hacky but it works.
1. In the code of the gem in file `favicon_generator.rb` get the JSON to be send via `puts` or write it to a file via running the generator (which will fail, but you get the JSON)
2. Send the POST-Request to the API-URL via a rest client (such as Postman) with the JSON from step 1 as HTTP body.
3. Copy & Paste the response body to a file
4. Insert `JSON.parse(File.read("path/to/file"))` in the gem code instead of the real HTTP request. So that the JSON is returned.
5. Run the generator again and everything will be set up as wanted.
